// ACA Ledger — strict append-only mirror writer for `user_aca_records`.
//
// CONTRACT:
// - Does NOT generate ACA hashes. The hash + payload MUST come from
//   `src/utils/acaGenerator.ts` (hardware-anchored on native, simulated on web).
// - Strict standard INSERT — no upsert, no conflict resolution. A duplicate
//   hash will throw; callers should treat that as a logical error.
// - Always populates every writable column with an explicit value so rows
//   never silently fall back to schema defaults ('unknown' source, KYC scopes).
//
// Call this once at every consent touchpoint immediately after generateACAHash
// resolves successfully. Pass a stable, descriptive `sourceId`.

import { supabase } from "@/integrations/supabase/client";

export interface ACARecordInput {
  /** Authenticated user id (also the FK platform_guid). */
  userId: string;
  /** Stable surface identifier, e.g. `GOV_COMMITTEE_APPLY`, `DUNA_WELCOME`. */
  sourceId: string;
  /** Logical event class, e.g. `COMMITTEE_APPLICATION_V1`. Nullable column. */
  consentType?: string | null;
  /** ACA hash (64-char hex). Pre-generated by acaGenerator. */
  hash: string;
  /** Full payload returned by acaGenerator (used to lift consent_scope/timestamp). */
  payload: {
    consent_scope?: string[];
    timestamp?: string;
  } & Record<string, unknown>;
  /** Optional on-chain settlement reference. */
  txHash?: string | null;
}

export async function recordACA(input: ACARecordInput): Promise<void> {
  const row = {
    platform_guid: input.userId,
    aca_hash_key: input.hash,
    source_id: input.sourceId,
    consent_type: input.consentType ?? null,
    consent_scope: Array.isArray(input.payload?.consent_scope) && input.payload.consent_scope.length > 0
      ? input.payload.consent_scope
      : ["GENERAL_CONSENT"],
    created_at: input.payload?.timestamp ?? new Date().toISOString(),
    tx_hash: input.txHash ?? null,
  };

  console.log(
    `[ACA_LEDGER] INSERT source=${input.sourceId} hash=${input.hash.substring(0, 8)}…`,
  );

  const { error } = await (supabase as any)
    .from("user_aca_records")
    .insert(row);

  if (error) {
    console.error(`[ACA_LEDGER] INSERT_FAILED source=${input.sourceId}`, error);
    throw new Error(`ACA mirror failed: ${error.message}`);
  }
}
