
-- Create the device_events table for ingesting disparate data types
CREATE TABLE public.device_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    event_type TEXT NOT NULL,
    event_timestamp TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    json_payload JSONB NOT NULL,
    processed_at TIMESTAMPTZ
);

-- Add comments for clarity
COMMENT ON TABLE public.device_events IS 'Stores time-series data events from user devices.';
COMMENT ON COLUMN public.device_events.event_type IS 'The type of event, e.g., ''BATTERY_STATUS'', ''LOCATION_UPDATE'', ''MOTION_DATA''.';
COMMENT ON COLUMN public.device_events.json_payload IS 'A flexible JSON object containing the specific data for the event type.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.device_events ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
CREATE POLICY "Users can insert their own device events"
ON public.device_events FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own device events"
ON public.device_events FOR SELECT
USING (auth.uid() = user_id);
