// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Vanity auth domain — masks the raw Supabase URL in Apple/Google sign-in sheets.
const SUPABASE_URL = "https://auth.thebigidia.com";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_L_foF7A1ds9WBnsVnvcNVA_JYrRwm8B";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});